//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public int billNumber { get; set; }
        public Nullable<int> vendorId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
