//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateProduct
    {
        public int productId { get; set; }
        public int estimateId { get; set; }
        public string quantity { get; set; }
    
        public virtual Estimate Estimate { get; set; }
        public virtual Product Product { get; set; }
    }
}
