//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estimate()
        {
            this.EstimateProducts = new HashSet<EstimateProduct>();
        }
    
        public int id { get; set; }
        public Nullable<int> customerId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> expiresOn { get; set; }
        public string subHeading { get; set; }
        public string footer { get; set; }
        public string memo { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateProduct> EstimateProducts { get; set; }
    }
}
