//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public Nullable<bool> incomeExpense { get; set; }
        public Nullable<int> salesTax { get; set; }
        public string description { get; set; }
        public string account { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> depositWithdrawal { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string category { get; set; }
        public string notes { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> vendorId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
